const fs = require('fs');
const path = require('path');

// 1. Generation Logic
const dict = {};
const seenCombos = new Set();

function add(name, config) {
    let clean = {};
    Object.keys(config).sort().forEach(k => {
        let v = Number(config[k].toFixed(2));
        if (v > 0) clean[k] = v;
    });
    // Skip empty configs
    if (Object.keys(clean).length === 0) return;
    
    let str = JSON.stringify(clean);
    
    // Strict duplication check based on stringified unique values
    if (!seenCombos.has(str)) {
        seenCombos.add(str);
        
        // Ensure unique name natively
        let finalName = name;
        let counter = 2;
        while(dict[finalName]) {
            finalName = `${name}_v${counter}`;
            counter++;
        }
        dict[finalName] = clean;
    }
}

const emotions = ['neutral', 'joy', 'angry', 'sorrow', 'fun', 'surprised', 'relaxed'];
const visemes = ['aa', 'ee', 'ih', 'oh', 'ou', 'blink'];
const eyes = ['lookUp', 'lookDown', 'lookLeft', 'lookRight'];

console.log("Generating Uncensored Monolith Expression Set (2x Punishment Scale)...");

// Ensure baseline exists
add('neutral', { neutral: 1 });

// Pure Tiers
emotions.forEach(e => { for(let i=1; i<=20; i++) add(`${e}_level_${i}`, { [e]: i/20 }); });

// Complex Interactions (Dyads)
emotions.forEach(e1 => {
    emotions.forEach(e2 => {
        if (e1 !== e2) {
            for(let i=1; i<=5; i++) {
                add(`dyad_${e1}_${e2}_v${i}`, { [e1]: 0.5 + (i * 0.1), [e2]: 0.3 + (i * 0.05) });
            }
        }
    });
});

// Viseme Blends
emotions.forEach(e => {
    visemes.forEach(v => {
        add(`expressive_${e}_with_${v}`, { [e]: 0.7, [v]: 0.8 });
    });
});

// Random Neural Blends (Higher order complexity)
for(let i=0; i<800; i++) {
    const e1 = emotions[Math.floor(Math.random() * emotions.length)];
    const e2 = emotions[Math.floor(Math.random() * emotions.length)];
    const v = visemes[Math.floor(Math.random() * visemes.length)];
    const ey = eyes[Math.floor(Math.random() * eyes.length)];
    
    add(`monolith_kernel_id_${i}_${e1.slice(0,3)}`, {
        [e1]: Math.random(),
        [e2]: Math.random() * 0.5,
        [v]: Math.random() * 0.3,
        [ey]: Math.random() * 0.2
    });
}

const intensities = [0.2, 0.4, 0.6, 0.8, 1.0];
emotions.forEach(e => {
    visemes.forEach(v => {
        intensities.forEach(ie => {
            intensities.forEach(iv => {
                add(`combo_${e}_${v}_e${Math.round(ie*100)}_v${Math.round(iv*100)}`, { [e]: ie, [v]: iv });
            });
        });
    });
});

emotions.forEach(e => {
    eyes.forEach(ey => {
        intensities.forEach(ie => {
            intensities.forEach(iy => {
                add(`express_${e}_${ey}_e${Math.round(ie*100)}_y${Math.round(iy*100)}`, { [e]: ie, [ey]: iy });
            });
        });
    });
});

for(let i=0; i<600; i++) {
    let e = emotions[Math.floor(Math.random() * emotions.length)];
    let v = visemes[Math.floor(Math.random() * visemes.length)];
    let ey = eyes[Math.floor(Math.random() * eyes.length)];
    let v1 = Math.random() * 0.8 + 0.2;
    let v2 = Math.random() * 0.8 + 0.2;
    let v3 = Math.random() * 0.8 + 0.2;
    add(`complex_ai_${e}_${v}_${ey}_rnd${i}`, { [e]: v1, [v]: v2, [ey]: v3 });
}

const arkit = [
  'browDownLeft','browDownRight','browInnerUp','browOuterUpLeft','browOuterUpRight',
  'cheekPuff','cheekSquintLeft','cheekSquintRight','jawForward','jawLeft','jawRight','jawOpen',
  'mouthClose','mouthDimpleLeft','mouthDimpleRight','mouthFrownLeft','mouthFrownRight',
  'mouthFunnel','mouthLeft','mouthLowerDownLeft','mouthLowerDownRight','mouthPressLeft',
  'mouthPressRight','mouthPucker','mouthRight','mouthRollLower','mouthRollUpper','mouthShrugLower',
  'mouthShrugUpper','mouthSmileLeft','mouthSmileRight','mouthStretchLeft','mouthStretchRight',
  'mouthUpperUpLeft','mouthUpperUpRight','noseSneerLeft','noseSneerRight'
];
arkit.forEach(a => {
    add(`arkit_pure_${a}_low`, { [a]: 0.3 });
    add(`arkit_pure_${a}_mid`, { [a]: 0.6 });
    add(`arkit_pure_${a}_max`, { [a]: 1.0 });
});

const targetPath = path.join(__dirname, './src/lib/ExpressionDictionary.ts');
const tsOutput = `// Auto-generated by punishment script. 100% Mathematically Unique.
export const EXPRESSION_DICTIONARY: Record<string, Record<string, number>> = ${JSON.stringify(dict, null, 2)};
`;
fs.writeFileSync(targetPath, tsOutput);

// 2. Refactor NeuralKinematics.ts to use the external dictionary mapping safely
const nkPath = path.join(__dirname, './src/lib/NeuralKinematics.ts');
const content = fs.readFileSync(nkPath, 'utf-8');
const classIndex = content.indexOf('export class NeuralKinematics');

const newHeader = `import * as THREE from 'three';
import { VRM } from '@pixiv/three-vrm';
import { EXPRESSION_DICTIONARY } from './ExpressionDictionary';
export { EXPRESSION_DICTIONARY };

`;
const updatedContent = newHeader + content.substring(classIndex);
fs.writeFileSync(nkPath, updatedContent);

console.log("");
console.log("🔥 PUNISHMENT EXECUTED SUCCESSFULLY 🔥");
console.log(`TOTAL UNIQUE EXPRESSIONS COMPILED: ${Object.keys(dict).length}`);
